version: '3.9'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devDB
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  app:
    build:
      context: .
      args:
        - DEV=True
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=devDB
      - DB_USER=devuser
      - DB_PASS=changeme
    command:
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  dev-db-data:
